# Generated by Django 4.1.1 on 2022-09-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
                ('proxy', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=20)),
            ],
        ),
    ]
